In [5]:
import numpy as np
import sys

In [7]:
np.__version__

'1.20.3'

In [6]:
sys.version

'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

In [12]:
array1 = np.ones(4)

In [13]:
array2 = np.arange(15)

In [15]:
array_conc = np.concatenate((array1, array2))

In [17]:
array_conc.astype(int)

array([ 1,  1,  1,  1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14])

In [18]:
array3 = np.ones((3,3))

In [19]:
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
array4 = np.zeros((3,3))

In [21]:
array4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
array_teste = np.array([np.arange(3),np.arange(3)])

In [26]:
array_teste

array([[0, 1, 2],
       [0, 1, 2]])

In [28]:
np.vstack((array3,array4))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.hstack((array4,array3))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [30]:
array5 = np.array([1,2,3]);
array6 = np.array([4,5,6]);
array7 = np.array([7,8,9]);

In [31]:
np.row_stack((array5,array6,array7))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.column_stack((array5,array6,array7))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
array8 = np.arange(16);
array8 = array8.reshape((4,4))

In [52]:
[array9,array10] = np.hsplit(array8,2)

In [53]:
array9

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [54]:
array10

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [50]:
[array11,array12] = np.vsplit(array8,2)

In [51]:
array11

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])