In [1]:
import numpy as np
import sys

In [2]:
np.__version__

'1.20.3'

In [4]:
sys.version

'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

In [5]:
array1 = np.arange(1,50,5)

In [6]:
array1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [8]:
array1.min()

1

In [9]:
array1.max()

46

In [10]:
array1.mean()

23.5

In [11]:
array1.sum()

235

In [12]:
array1.std()

14.361406616345072

In [13]:
?array1

In [14]:
[x**5 for x in array1]

[1,
 7776,
 161051,
 1048576,
 4084101,
 11881376,
 28629151,
 60466176,
 115856201,
 205962976]

In [33]:
array2 = [x**5 for x in array1 if x%2!=0]

In [23]:
list(filter(lambda x:x%2!=0,array2))

[1, 161051, 4084101, 28629151, 115856201]

In [34]:
array2

[1, 161051, 4084101, 28629151, 115856201]

In [44]:
array4 = np.arange(0,10)

In [45]:
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array4[array4%2==0]

array([0, 2, 4, 6, 8])