In [2]:
import numpy as np;
import sys

In [3]:
sys.version

'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

In [7]:
np.__version__

'1.20.3'

In [11]:
matriz1 = np.matrix("1,2,3; 3,2,1")

In [12]:
matriz1

matrix([[1, 2, 3],
        [3, 2, 1]])

In [15]:
matriz2= np.matrix([[1,2,3],[3,2,1]])

In [16]:
matriz2

matrix([[1, 2, 3],
        [3, 2, 1]])

In [17]:
matriz3 = np.matrix([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])

In [19]:
print(matriz3)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [23]:
print(matriz3[2:,:2])

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [24]:
a = np.array([[1,2,3],[1,2,3]])

In [25]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [26]:
b = a*matriz3[3:,3:]

In [27]:
b

matrix([[24, 30, 36],
        [24, 30, 36]])

In [28]:
matriz10 = np.mat(b)

In [29]:
print(matriz10)

[[24 30 36]
 [24 30 36]]
