# COMPUTAÇÃO COM NUMPY

In [5]:
#Importando o modulo numpy
import numpy as np

# CRIANDO ESTRUTURAS DE DADOS COM NUMPY

In [2]:
#Criando um array unidimensional
array1 = np.array([10,20,30,40])
#Criando um array bidimensional
array2 = np.array([[10,20,30],[40,50,60]])

In [3]:
#Imprimindo os arrays
print(array1)
print(array2)

[10 20 30 40]
[[10 20 30]
 [40 50 60]]


In [6]:
#Atributo de formato para o array 1
array1.shape

(4,)

In [7]:
#Atributo de formato para o array 2
array2.shape

(2, 3)

In [8]:
#Atributo de dimensões para o array1
array1.ndim

1

In [9]:
#Atributo de dimensões para o array2
array2.ndim

2

In [10]:
#Método maximo para o array numero 2
array2.max()

60

## ESTRUTURAS DE DADOS COM ARANGE

In [12]:
array3 = np.arange(15)

In [13]:
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
array4 = np.arange(0,16,5)

In [17]:
print(array4)

[ 0  5 10 15]


In [19]:
array5 = np.linspace(0,1000,3);
print(array5)

[   0.  500. 1000.]


In [20]:
array6 = np.zeros((5,5));
print(array6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
array7 = np.ones((3,3,3));
print(array7)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
array8 = np.eye(5);
print(array8)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
array9 = np.diag((1,2,3,4,5,6));
print(array9)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [26]:
array10 = np.random.rand(6);
print(array10)

[0.0801068  0.08388202 0.93138867 0.79559803 0.00920271 0.83086227]


In [27]:
array11 = np.random.randn(10);
print(array11)

[ 0.60303915 -0.44899554  0.87738734  1.11452591  1.70968657  1.50488094
 -0.5135297  -0.79278573 -0.84918583  1.99180657]


In [36]:
array13 = np.empty((3,2));
print(array13)

[[0.0801068  0.08388202]
 [0.93138867 0.79559803]
 [0.00920271 0.83086227]]


In [38]:
array14 = np.array([[1,2,3],[2,3,4]]);
array15= np.tile(array14,(4,4))
print(array15)

[[1 2 3 1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4 2 3 4]
 [1 2 3 1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4 2 3 4]
 [1 2 3 1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4 2 3 4]
 [1 2 3 1 2 3 1 2 3 1 2 3]
 [2 3 4 2 3 4 2 3 4 2 3 4]]


In [6]:
array16 = np.array([1,2,3,4,5], dtype= 'float');
print(array16)

[1. 2. 3. 4. 5.]


In [7]:
array16.dtype

dtype('float64')

# OPERAÇÕES COM ARRAY

In [9]:
array20 = np.array([1,2,3,4,5])*2

In [10]:
array20

array([ 2,  4,  6,  8, 10])

In [11]:
array21 = np.arange(0,5)*10;
array21

array([ 0, 10, 20, 30, 40])

In [18]:
array22 = np.arange(0,10)**10;
array22

array([         0,          1,       1024,      59049,    1048576,
          9765625,   60466176,  282475249, 1073741824, -808182895],
      dtype=int32)

In [19]:
array23 = np.arange(0,10)**10;
array23

array([         0,          1,       1024,      59049,    1048576,
          9765625,   60466176,  282475249, 1073741824, -808182895],
      dtype=int32)

In [20]:
array24 = array23 - array22;
array24

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [21]:
array24>array23

array([False, False, False, False, False, False, False, False, False,
        True])

In [22]:
array25 = np.arange(0,100);
%timeit array25**10

4.14 µs ± 152 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
array26 = np.arange(0,100);
%timeit [array26[x]**10 for x in array26]

101 µs ± 5.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
