# INDEXAÇÃO E SLICING COM NUMPY

In [3]:
import numpy as np

In [5]:
array1 = np.arange(0,10)**2

In [9]:
print(array1);
print(array1[1]);
print(array1[0]);
print(array1[-1])

[ 0  1  4  9 16 25 36 49 64 81]
1
0
81


In [25]:
array2 = np.arange(1,1000);
array2.sort();
array2[::-1][-1]

1

In [4]:
array3 = np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10)])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array3.ndim

2

In [6]:
array3[1:,1:]

array([[5, 6],
       [8, 9]])

In [9]:
array3[1,1]=100;
print(array3);

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [13]:
array8 = np.arange(0,15,2)

In [14]:
array8

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [15]:
array9 = array8[::3]

In [16]:
array9

array([ 0,  6, 12])

In [18]:
array10 = array9.copy()

In [19]:
array10

array([ 0,  6, 12])