In [2]:
import numpy as np

In [5]:
array1 = np.array([np.arange(10,50,10),np.arange(10,50,10)])

In [6]:
array1

array([[10, 20, 30, 40],
       [10, 20, 30, 40]])

In [17]:
array2 = np.transpose(array1)

In [18]:
print(array2)

[[10 10]
 [20 20]
 [30 30]
 [40 40]]


In [19]:
array2.ravel()

array([10, 10, 20, 20, 30, 30, 40, 40])

In [20]:
array2.T.ravel()

array([10, 20, 30, 40, 10, 20, 30, 40])

In [21]:
array3 = np.random.randint(2,20,size=(4,4))

In [22]:
array3

array([[ 3, 10,  4,  4],
       [13,  3, 11,  3],
       [19, 15, 17,  8],
       [ 9, 11,  5,  4]])

In [27]:
array4 = np.all((array3/3)==1)

In [28]:
array4

False

In [42]:
array5 = np.arange(1,11,3)

In [43]:
array5

array([ 1,  4,  7, 10])

In [75]:
array6 = np.array([[2,4,1,1,3],[2,4,1,1,3]])

In [76]:
array6

array([[2, 4, 1, 1, 3],
       [2, 4, 1, 1, 3]])

In [77]:
array6.sort(axis=0)

In [78]:
array6

array([[2, 4, 1, 1, 3],
       [2, 4, 1, 1, 3]])